name: Budowanie Dockera

on:
  push:
    branches:
      - master

jobs:
  budowanie:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v2

      - name: Konfiguracja QEMU
        uses: docker/setup-qemu-action@v2

      - name: Konfiguracja Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Logowanie do Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Budowanie i przesyłanie obrazu Dockera dla amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gajewski/second_task_pg:linux-amd64
          platforms: linux/amd64
          builder: default
          driver: docker-container

      - name: Budowanie i przesyłanie obrazu Dockera dla arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gajewski/second_task_pg:linux-arm64
          platforms: linux/arm64
          builder: default
          driver: docker-container
